namespace SerpentsEyes.Core.GameData;

/// <summary>
/// Static database of game content extracted from Serpent's Gaze asset files.
/// The data half of this partial class lives in TagDatabase.g.cs, regenerated by
/// running tools/SerpentsEyes.Extractor against an unpacked copy of the game.
/// </summary>
public static partial class TagDatabase
{
    // Lazy: static-field initialization order across partial-class files is not
    // guaranteed, and the data arrays live in the generated half of this class.
    // Lazy<T> rather than "??=" because the app reads these from a background parse
    // thread as well as the UI thread, and a torn read would hand back a half-built
    // dictionary.
    private static readonly Lazy<Dictionary<string, GameTagInfo>> ByTag = new(BuildByTag);
    private static readonly Lazy<Dictionary<string, GameTagInfo>> ByInternalId = new(BuildByInternalId);
    private static readonly Lazy<Dictionary<string, string>> MapTitles = new(BuildMapTitles);

    private static Dictionary<string, GameTagInfo> ByTagLookup => ByTag.Value;
    private static Dictionary<string, GameTagInfo> ByInternalIdLookup => ByInternalId.Value;
    private static Dictionary<string, string> MapTitleLookup => MapTitles.Value;

    /// <summary>All known tags, in extraction order.</summary>
    public static IReadOnlyList<GameTagInfo> All => Entries;

    /// <summary>The seven gods ("Divinities"), including statue-less Sael.</summary>
    public static IReadOnlyList<GodInfo> Gods => GodEntries;

    /// <summary>Real in-game blessing lock rules, keyed by boss-kill threshold (1 and 3).</summary>
    public static IReadOnlyDictionary<int, string> BlessingLockRules => BlessingLockRuleEntries;

    /// <summary>Looks up a Divinity by key, e.g. "Matriarch". Case-insensitive; null if unknown.</summary>
    public static GodInfo? FindGod(string key)
        => GodEntries.FirstOrDefault(g => string.Equals(g.Key, key, StringComparison.OrdinalIgnoreCase));

    /// <summary>Looks up a tag, e.g. "Progression.Blessing.ChanceHoT".</summary>
    /// <param name="tag">Full progression tag.</param>
    /// <param name="info">The matching entry when found.</param>
    /// <returns>True when the tag is known to the database.</returns>
    public static bool TryGet(string tag, out GameTagInfo info)
        => ByTagLookup.TryGetValue(tag, out info!);

    /// <summary>Looks up a tag, e.g. "Progression.Blessing.ChanceHoT", or null if unknown.</summary>
    public static GameTagInfo? Find(string tag)
        => ByTagLookup.GetValueOrDefault(tag);

    /// <summary>Looks up by internal asset id, e.g. "Tree_Warhammer" or "Class_Stronk" (loadout ids).</summary>
    public static GameTagInfo? FindByInternalId(string internalId)
        => ByInternalIdLookup.GetValueOrDefault(internalId);

    /// <summary>Resolves a save-file map name like "Majin_HolyCity" to its in-game title ("Namah, City of Pilgrims").</summary>
    public static string? MapTitle(string internalLevelName)
        => MapTitleLookup.GetValueOrDefault(Normalize(internalLevelName));

    private static Dictionary<string, GameTagInfo> BuildByTag()
    {
        var dict = new Dictionary<string, GameTagInfo>(Entries.Length, StringComparer.Ordinal);
        foreach (var entry in Entries)
        {
            dict[entry.Tag] = entry;
        }
        return dict;
    }

    private static Dictionary<string, GameTagInfo> BuildByInternalId()
    {
        var dict = new Dictionary<string, GameTagInfo>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in Entries)
        {
            foreach (string id in entry.InternalIds)
            {
                dict[id] = entry;
            }
        }
        return dict;
    }

    private static Dictionary<string, string> BuildMapTitles()
    {
        var dict = new Dictionary<string, string>(MapTitleEntries.Length, StringComparer.Ordinal);
        foreach (var (key, title) in MapTitleEntries)
        {
            dict[key] = title;
        }
        return dict;
    }

    private static string Normalize(string levelName)
        => levelName.Replace("_", "").ToLowerInvariant();
}
