namespace SerpentsEyes.Core.GameData;

/// <summary>
/// Static database of game content extracted from Serpent's Gaze asset files.
/// The data half of this partial class lives in TagDatabase.g.cs, regenerated by
/// running tools/SerpentsEyes.Extractor against an unpacked copy of the game.
/// </summary>
public static partial class TagDatabase
{
    // Lazy: static-field initialization order across partial-class files is not
    // guaranteed, and the data arrays live in the generated half of this class.
    private static Dictionary<string, GameTagInfo>? _byTag;
    private static Dictionary<string, GameTagInfo>? _byInternalId;
    private static Dictionary<string, string>? _mapTitles;

    private static Dictionary<string, GameTagInfo> ByTagLookup => _byTag ??= BuildByTag();
    private static Dictionary<string, GameTagInfo> ByInternalIdLookup => _byInternalId ??= BuildByInternalId();
    private static Dictionary<string, string> MapTitleLookup => _mapTitles ??= BuildMapTitles();

    /// <summary>All known tags, in extraction order.</summary>
    public static IReadOnlyList<GameTagInfo> All => Entries;

    public static bool TryGet(string tag, out GameTagInfo info)
        => ByTagLookup.TryGetValue(tag, out info!);

    public static GameTagInfo? Find(string tag)
        => ByTagLookup.GetValueOrDefault(tag);

    /// <summary>Looks up by internal asset id, e.g. "Tree_Warhammer" or "Class_Stronk" (loadout ids).</summary>
    public static GameTagInfo? FindByInternalId(string internalId)
        => ByInternalIdLookup.GetValueOrDefault(internalId);

    /// <summary>Resolves a save-file map name like "Majin_HolyCity" to its in-game title ("Namah, City of Pilgrims").</summary>
    public static string? MapTitle(string internalLevelName)
        => MapTitleLookup.GetValueOrDefault(Normalize(internalLevelName));

    private static Dictionary<string, GameTagInfo> BuildByTag()
    {
        var dict = new Dictionary<string, GameTagInfo>(Entries.Length, StringComparer.Ordinal);
        foreach (var entry in Entries)
        {
            dict[entry.Tag] = entry;
        }
        return dict;
    }

    private static Dictionary<string, GameTagInfo> BuildByInternalId()
    {
        var dict = new Dictionary<string, GameTagInfo>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in Entries)
        {
            foreach (string id in entry.InternalIds)
            {
                dict[id] = entry;
            }
        }
        return dict;
    }

    private static Dictionary<string, string> BuildMapTitles()
    {
        var dict = new Dictionary<string, string>(MapTitleEntries.Length, StringComparer.Ordinal);
        foreach (var (key, title) in MapTitleEntries)
        {
            dict[key] = title;
        }
        return dict;
    }

    private static string Normalize(string levelName)
        => levelName.Replace("_", "").ToLowerInvariant();
}
